Run shellcheck

diff --git a/tdx b/tdx
--- a/tdx
+++ b/tdx
@@ -20,6 +20,7 @@ readonly BAT_THEME
 export SELF="$0"
 
 if [[ -z "${ZED_TERM:-}" ]]; then
+    # shellcheck disable=SC2140
     export FZF_DEFAULT_OPTS="--preview 'file=\$(echo {1}); [[ -f "\$file" ]] && bat --color=always --style=plain "\$file"' --preview-window 'bottom:border-sharp:wrap'"
 fi
 
@@ -41,15 +42,15 @@ function err {
 
 function check_dep {
     if ! command -v "$1" &> /dev/null; then
-        err "Couldn't find $1 in \$PATH: please make sure it's installed!"
-        exit 1
+	err "Couldn't find $1 in \$PATH: please make sure it's installed!"
+	exit 1
     fi
 }
 
 function check_lib {
     if [[ ! -f "$1" ]]; then
-        err "Couldn't find $1: please make sure it's available!"
-        exit 1
+	err "Couldn't find $1: please make sure it's available!"
+	exit 1
     fi
 }
 
@@ -76,7 +77,7 @@ function print_usage {
 function new {
     local template="${1:-}"
     if [[ -n "$template" ]]; then
-        shift
+	shift
     fi
 
     local path
@@ -89,8 +90,8 @@ function new {
     local full_path="$path/$filename"
 
     case "$template" in
-        n|note)
-            cat <<EOF >"$full_path"
+	n|note)
+	    cat <<EOF >"$full_path"
 ---
 title: ${1:-}
 collection: ${2:-}
@@ -100,9 +101,9 @@ publish: true
 ---
 
 EOF
-            ;;
-        t|task)
-            cat <<EOF >"$full_path"
+	    ;;
+	t|task)
+	    cat <<EOF >"$full_path"
 ---
 title: ${1:-}
 collection: ${2:-}
@@ -114,9 +115,9 @@ deadline:
 ---
 
 EOF
-            ;;
-        b|bookmark)
-            cat <<EOF >"$full_path"
+	    ;;
+	b|bookmark)
+	    cat <<EOF >"$full_path"
 ---
 title: ${1:-}
 url: ${2:-}
@@ -128,9 +129,9 @@ publish: true
 ---
 
 EOF
-            ;;
-        r|reminder)
-            cat <<EOF >"$full_path"
+	    ;;
+	r|reminder)
+	    cat <<EOF >"$full_path"
 ---
 title: ${1:-}
 when: ${2:-}
@@ -139,9 +140,9 @@ what: reminder
 ---
 
 EOF
-            ;;
-        p|pomo|pomodoro)
-            cat <<EOF >"$full_path"
+	    ;;
+	p|pomo|pomodoro)
+	    cat <<EOF >"$full_path"
 ---
 title: ${1:-}
 collection: ${2:-}
@@ -149,9 +150,9 @@ what: pomodoro
 ---
 
 EOF
-            ;;
-        m|meeting)
-            cat <<EOF >"$full_path"
+	    ;;
+	m|meeting)
+	    cat <<EOF >"$full_path"
 ---
 title: ${1:-}
 collection: ${2:-}
@@ -159,9 +160,9 @@ what: meeting
 ---
 
 EOF
-            ;;
-        *)
-            cat <<EOF >"$full_path"
+	    ;;
+	*)
+	    cat <<EOF >"$full_path"
 ---
 title: ${1:-}
 collection: ${2:-}
@@ -174,7 +175,7 @@ EOF
     "$EDITOR" "$full_path"
 
     if  [[ ! -s "$full_path" ]]; then
-        rm "$full_path"
+	rm "$full_path"
     fi
 }
 
@@ -204,7 +205,7 @@ ORDER BY
   mtime_s DESC,
   path ASC
 EOF
-             );
+	     );
 
     command=$(cat <<EOF
 /usr/bin/env \
@@ -212,14 +213,15 @@ EOF
   ".load ${TDX_MDF%.so}" \
   "$sql_query"
 EOF
-           );
+	   );
 
     (
-        export FZF_DEFAULT_COMMAND="$command";
-        fzf --bind 'ctrl-r:reload(eval "$FZF_DEFAULT_COMMAND")' \
-            --bind 'enter:execute(eval "$SELF e {1}")+reload(eval "$FZF_DEFAULT_COMMAND")' \
-            --bind 'ctrl-n:execute(eval "$SELF n")' \
-            --info inline-right
+	export FZF_DEFAULT_COMMAND="$command";
+	# shellcheck disable=SC2016
+	fzf --bind 'ctrl-r:reload(eval "$FZF_DEFAULT_COMMAND")' \
+	    --bind 'enter:execute(eval "$SELF e {1}")+reload(eval "$FZF_DEFAULT_COMMAND")' \
+	    --bind 'ctrl-n:execute(eval "$SELF n")' \
+	    --info inline-right
     )
 
 }
@@ -234,13 +236,13 @@ function edit {
     local final_path
 
     if [[ "$path" == *".md" ]]; then
-        final_path="$path"
+	final_path="$path"
     else
-        final_path="${path}.md"
+	final_path="${path}.md"
     fi
 
     if [[ ! -f "$final_path" ]]; then
-        cat <<EOF >"$final_path"
+	cat <<EOF >"$final_path"
 ---
 title:
 ---
@@ -272,18 +274,18 @@ EOF
 )"
 
     "$SELF" sql "-list" ".separator \n" "$query" \
-        | tr -d '\r' > "$related";
+	| tr -d '\r' > "$related";
     chmod -w "$related"
 
     if [[ ! -s "$related" ]]; then
-        rm -f "$related"
-        "$EDITOR" "$final_path"
+	rm -f "$related"
+	"$EDITOR" "$final_path"
     else
-        "$EDITOR" "$final_path" "$related"
+	"$EDITOR" "$final_path" "$related"
     fi
 
     if [[ ! -s "$final_path" ]]; then
-        rm "$final_path"
+	rm "$final_path"
     fi
 
     rm -f "$related"
@@ -298,7 +300,7 @@ function journal {
     mkdir -p "$parent_dir"
 
     if [[ ! -f "$path" ]]; then
-        cat <<EOF >"$path"
+	cat <<EOF >"$path"
 ---
 title: $(date +%F)
 ---
@@ -334,7 +336,7 @@ EOF
     "$EDITOR" "$path"
 
     if [[ ! -s "$path" ]]; then
-        rm "$path"
+	rm "$path"
     fi
 }
 
@@ -343,33 +345,32 @@ function notify {
     local summary="$2"
 
     local ns
-    ns=$(which notify-send)
-    if (( $? != 0 )); then
-        return
+    if ! which notify-send; then
+	return
     fi
 
     "$ns" --app-name "tdx" \
-          -u "normal" \
-          --action="action1=Focus Window" \
-          "$title" \
-          "$summary"
+	  -u "normal" \
+	  --action="action1=Focus Window" \
+	  "$title" \
+	  "$summary"
 }
 
 function pomodoro {
     while true; do
-        clear
+	clear
 
-        echo
-        echo -e "  \033[32m.v,\033[0m"
-        echo -e " \033[31m(\033[0m' \033[31m,)\033[0m"
-        echo
+	echo
+	echo -e "  \033[32m.v,\033[0m"
+	echo -e " \033[31m(\033[0m' \033[31m,)\033[0m"
+	echo
 
-        local location
-        location=$(pwd)
+	local location
+	location=$(pwd)
 
-        echo -e "\e[4mRecent pomodoros:\e[0m"
-        local sql_query
-        sql_query=$(cat <<EOF
+	echo -e "\e[4mRecent pomodoros:\e[0m"
+	local sql_query
+	sql_query=$(cat <<EOF
 SELECT
   substr(path, length('$location') + 2), ' / ',
   mdf_front_matter(path, 'title'), ' #',
@@ -392,42 +393,42 @@ EOF
 	    "$sql_query"
 	echo
 
-        echo -ne "\033[4mPomodoro goal?\033[0m\n"
-        local purpose
-        read -e -r purpose
+	echo -ne "\033[4mPomodoro goal?\033[0m\n"
+	local purpose
+	read -e -r purpose
 
-        local collection
-        echo -ne "\033[4mAdd to collection?\033[0m\n"
-        read -e -r collection
+	local collection
+	echo -ne "\033[4mAdd to collection?\033[0m\n"
+	read -e -r collection
 
-        local end_time
-        end_time="$(date -d "+25 minutes")"
+	local end_time
+	end_time="$(date -d "+25 minutes")"
 
-        local end_timestamp
-        end_timestamp="$(date -d "$end_time" +%s)"
+	local end_timestamp
+	end_timestamp="$(date -d "$end_time" +%s)"
 
-        echo -e "\n> Pomodoro will end at ${end_time}"
-        echo -n "> "
-        while (( $(date +%s) < end_timestamp )); do
-            sleep 60
-            echo -n "."
-        done
-        echo -e '\a'
-        notify "Pomodoro finished!" "${collection+$collection\n}$purpose"
+	echo -e "\n> Pomodoro will end at ${end_time}"
+	echo -n "> "
+	while (( $(date +%s) < end_timestamp )); do
+	    sleep 60
+	    echo -n "."
+	done
+	echo -e '\a'
+	notify "Pomodoro finished!" "${collection+$collection\n}$purpose"
 
-        $SELF new pomodoro "$purpose" "$collection"
-        echo -e "> Recorded.\n"
+	$SELF new pomodoro "$purpose" "$collection"
+	echo -e "> Recorded.\n"
 
-        end_time="$(date -d "+5 minutes")"
-        end_timestamp="$(date -d "$end_time" +%s)"
-        echo "> Break will end at ${end_time}"
-        echo -n "> "
-        while (( $(date +%s) < end_timestamp )); do
-            sleep 60
-            echo -n "."
-        done
-        echo -e "\a\n\n"
-        notify "Break finished!" "$(date)"
+	end_time="$(date -d "+5 minutes")"
+	end_timestamp="$(date -d "$end_time" +%s)"
+	echo "> Break will end at ${end_time}"
+	echo -n "> "
+	while (( $(date +%s) < end_timestamp )); do
+	    sleep 60
+	    echo -n "."
+	done
+	echo -e "\a\n\n"
+	notify "Break finished!" "$(date)"
     done
 }
 
@@ -452,17 +453,18 @@ WHERE
 GROUP BY 1
 ORDER BY COUNT(1) DESC
 EOF
-         )
+	 )
     local vals
     vals="$("$SELF" sql "-list" "$query")"
 
+    # shellcheck disable=SC2016
     for val in $vals; do
-        echo -e "=== ${val} ==="
-        "$SELF" sql "-list" ".separator ' '" "SELECT path, mdf_front_matter(path, 'title'), mdf_front_matter(path, 'collection'), mdf_front_matter(path, 'tags') FROM markdown_files WHERE mdf_front_matter(path, '$group_by') = '$val' AND basename LIKE '%.md' AND path NOT LIKE '%.git%' ${2:+AND $2} ORDER BY mtime_s DESC"
-        echo
+	echo -e "=== ${val} ==="
+	"$SELF" sql "-list" ".separator ' '" "SELECT path, mdf_front_matter(path, 'title'), mdf_front_matter(path, 'collection'), mdf_front_matter(path, 'tags') FROM markdown_files WHERE mdf_front_matter(path, '$group_by') = '$val' AND basename LIKE '%.md' AND path NOT LIKE '%.git%' ${2:+AND $2} ORDER BY mtime_s DESC"
+	echo
     done |\
-        fzf --bind 'enter:execute(eval "$SELF e {1}")+become(eval "$SELF b $group_by")' \
-            --info inline-right
+	fzf --bind 'enter:execute(eval "$SELF e {1}")+become(eval "$SELF b $group_by")' \
+	    --info inline-right
 }
 
 function tasks {
@@ -472,9 +474,10 @@ function tasks {
     local location
     location=$(pwd)
 
+    # shellcheck disable=2016
     for when in "${whens[@]}"; do
-        local group_query
-        group_query="$(cat <<EOF
+	local group_query
+	group_query="$(cat <<EOF
 SELECT
   printf('%-28s', substr(path, length('$location') + 2)),
   printf('>%-10s  ', mdf_front_matter(path, 'deadline')),
@@ -492,15 +495,15 @@ WHERE
 ORDER BY
   mtime_s DESC
 EOF
-        )";
-        printf "=== %-20s ===\n" "$when"
-        "$SELF" sql "-list" ".separator ' '" "$group_query"
-        echo
+	)";
+	printf "=== %-20s ===\n" "$when"
+	"$SELF" sql "-list" ".separator ' '" "$group_query"
+	echo
     done |\
-        fzf --bind "enter:become(eval \"$SELF e {1} && $SELF t $collection\")" \
-            --bind "ctrl-n:become(eval \"$SELF n t '' $collection && $SELF t $collection\")" \
-	    --with-nth "2.."
-            --info inline-right
+	fzf --bind "enter:become(eval \"$SELF e {1} && $SELF t $collection\")" \
+	    --bind "ctrl-n:become(eval \"$SELF n t '' $collection && $SELF t $collection\")" \
+	    --with-nth "2.." \
+	    --info inline-right
 }
 
 function week {
@@ -530,6 +533,7 @@ EOF
 function ripgrep {
   RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
   INITIAL_QUERY="${*:-}"
+  # shellcheck disable=SC2016
   fzf --ansi --disabled --query "$INITIAL_QUERY" \
       --bind "start:reload:$RG_PREFIX {q}" \
       --bind "change:reload:sleep 0.05; $RG_PREFIX {q} || true" \
@@ -546,45 +550,45 @@ function main {
     check_lib "$TDX_MDF"
 
     if (( $# < 1 )); then
-        print_usage
+	print_usage
     fi
 
     local basecmd="${1:-}"
     shift
 
     case "$basecmd" in
-        n|new)
-            new "$@"
-            ;;
-        e|edit)
-            edit "$@"
-            ;;
-        j|journal)
-            journal "$@"
-            ;;
-        q|query)
-            query "$@"
-            ;;
-        p|pomo|pomodoro)
-            pomodoro "$@"
-            ;;
-        s|sql)
-            sql "$@"
-            ;;
-        b|board)
-            board "$@"
-            ;;
-        t|tasks)
-            tasks "$@"
-            ;;
-        w|week)
-            week "$@"
-            ;;
-        r|ripgrep)
-            ripgrep "$@"
-            ;;
-        *)
-            print_usage
+	n|new)
+	    new "$@"
+	    ;;
+	e|edit)
+	    edit "$@"
+	    ;;
+	j|journal)
+	    journal "$@"
+	    ;;
+	q|query)
+	    query "$@"
+	    ;;
+	p|pomo|pomodoro)
+	    pomodoro "$@"
+	    ;;
+	s|sql)
+	    sql "$@"
+	    ;;
+	b|board)
+	    board "$@"
+	    ;;
+	t|tasks)
+	    tasks "$@"
+	    ;;
+	w|week)
+	    week "$@"
+	    ;;
+	r|ripgrep)
+	    ripgrep "$@"
+	    ;;
+	*)
+	    print_usage
     esac
 }
 
